name: Update JSDelivr Tag

on:
  push:
    branches:
      - qa
      - prod

jobs:
  update_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant permission to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }} # Use built-in GitHub token

      - name: Configure Git Identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get latest commit hash
        id: commit
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Update "latest" tag
        run: |
          git tag -fa latest -m "Updating to latest commit"
          git push origin --force latest
